In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'3.0.6'

In [4]:
!wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

--2026-10-05 08:54:07--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv.1’

car_fuel_efficiency 100%[===================>] 620.29K  --.-KB/s    in 0.1s

2026-10-05 08:54:10 (6.32 MB/s) - ‘car_fuel_efficiency_2026.csv.1’ saved [635180/635180]

In [5]:
!ls -lh

total 1.3M
-rw-rw-rw- 1 codespace codespace 621K Sep 30 09:50 car_fuel_efficiency_2026.csv
-rw-rw-rw- 1 codespace codespace 621K Oct  5 08:54 car_fuel_efficiency_2026.csv.1
-rw-rw-rw- 1 codespace codespace  29K Oct  5 08:53 homework1.ipynb

In [6]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')
df.head(9)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
5,2007,USA,Hybrid,Front-wheel drive,2,2290,6,266.0,4260,18.8,31.2
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
7,2005,USA,Gasoline,Front-wheel drive,4,2370,6,279.0,4090,17.4,30.2
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9

In [7]:
df.shape

(10000, 11)

In [8]:
df['fuel_type'].nunique()

3

In [9]:
df['fuel_type'].value_counts()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

In [10]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [11]:
df.isnull().any().sum()

np.int64(2)

In [12]:
df[df['origin']=='Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [13]:
df['horsepower'].median()

np.float64(254.0)

In [14]:
mode = df['horsepower'].mode()
print(mode)

0    252.0
Name: horsepower, dtype: float64

In [15]:
#before fillna 
df['horsepower'].isnull().any().sum()

np.int64(1)

In [16]:
df['horsepower'].fillna(mode)

0       243.0
1       272.0
2       267.0
3       258.0
4       304.0
        ...
9995    271.0
9996    244.0
9997    267.0
9998    270.0
9999    295.0
Name: horsepower, Length: 10000, dtype: float64

In [17]:
#after fillna
df['horsepower'].isnull().any().sum()

np.int64(1)

In [18]:
df['horsepower'].median()

np.float64(254.0)

In [19]:
list = ['vehicle_weight', 'model_year']
x = df[df['origin'] == 'Asia'][list].head(7)

In [20]:
x

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [21]:
transpose = x.T
transpose

                  2     6     8     10    15    16    22
vehicle_weight  4240  4310  4230  4420  3950  4750  4450
model_year      1996  1992  1997  1978  2007  2021  2019

In [22]:
XTX = transpose.dot(x)
XTX

                vehicle_weight  model_year
vehicle_weight       131950500    60750580
model_year            60750580    28041424

In [23]:
inv_XTX = np.linalg.inv(XTX)

In [24]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [25]:
res = inv_XTX.dot(transpose)
w = res.dot(y)
w

array([0.13644777, 0.2327492 ])

In [26]:
sum(w)

np.float64(0.36919696904925486)